tap "aws/tap"
tap "caskroom/cask"
tap "go-delve/delve"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "koekeishiya/formulae"
tap "kyoh86/tap"
tap "sbdchd/skim"
tap "tophat/bar"
tap "wakeful/selection"
tap "wata727/tflint"
brew "openssl"
brew "ansible"
brew "awscli"
brew "bat"
brew "go"
brew "exa"
brew "fasd"
brew "fd"
brew "gcc"
brew "htop"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "lolcat"
brew "mas"
brew "minikube"
brew "neovim"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "rust"
brew "terraform"
brew "terragrunt"
brew "tflint"
brew "tmux"
brew "tree"
brew "wget"
brew "yadm"
brew "yamllint"
brew "yarn", link: false
brew "zplug"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "aws/tap/aws-sam-cli"
brew "kyoh86/tap/richgo"
brew "sbdchd/skim/skim"
brew "tophat/bar/yvm"
brew "wakeful/selection/yaml2json"
cask "abricotine"
cask "alacritty"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "google-cloud-sdk"
cask "insomnia"
cask "minikube"
mas "Amphetamine", id: 937984704
mas "Brightness Slider", id: 456624497
mas "Coin Tick", id: 1141688067
mas "Flycut", id: 442160987
mas "Magnet", id: 441258766
mas "Medis", id: 1063631769
mas "Xcode", id: 497799835
