require('plugins')
require('opts')
require('keymaps')

require('configs.global')
require('configs.bufferline')
require('configs.mason')
require('configs.colorizer')
require('configs.nordic')
require('configs.lsp-installer')
require('configs.nvimtree')
require('configs.telescope')
require('impatient')

vim.cmd('colorscheme nordic')
vim.cmd('highlight Normal guibg=none')
vim.cmd('highlight NvimTreeNormal guibg=none')
vim.cmd('highlight TelescopeNormal guibg=none')
vim.cmd('highlight TelescopePreviewNormal guibg=none')
vim.cmd('highlight TelescopeBorder guibg=none')
